### ISSUE TITLE
Typo in Abstract Factory example code

### ISSUE THREAD

**Issue by paulio10** [tpf/perldotcom#110]
Hi, love the articles. Found a typo in the Abstract Factory code example just below "Here's the factory". There are *two* of the same "my $class =" assignments.  Since the first isn't needed, the code will work; it would just will throw a warning about redefining that variable. I would change the first one to "my $self =" instead, since it's not really needed. That way people's focus will be on the second one, not the first one.  Cheers!

**Comment by dnmfarrell** [comment]
Hey @paulio10 

Thanks for reporting this typo, I've fixed up the code as per your suggestion. A new site deploy is underway and the website should be updated in a few minutes.

David
