### ISSUE TITLE
Should this have a `cpanfile`?

### ISSUE THREAD

**Issue by oalders** [tpf/perldotcom#112]
I was able to get up and running very easily.  Like really easily. My only real hiccup was that I had to install some deps for `bin/q`.  I was able to do this for the most part by adding `use lazy;` to `bin/q` but I still manually had to install `DBD::SQLite`.  If you'd like me to add the deps from `bin/q` to a `cpanfile`, I'm happy to send a pull request.  That would make the setup time just a little bit faster.

**Comment by dnmfarrell** [comment]
That would be great, thanks. Anything to make it easier for contributors to get up and running
