### ISSUE TITLE
Change many MetaCPAN links to mcpan short code

### ISSUE THREAD

**Issue by briandfoy** [tpf/perldotcom#124]
Link to a Perl module like this instead of linking directly to a website:

     {{< mcpan "Test2::Tools" >}}

**Comment by dnmfarrell** [comment]
One thing about this, I think I made a mistake with this shortcode. It's more typing, but I think:

`[Test2::Tools]({{< mcpan "Test2::Tools" >}}) `

might be better, because then it's clear that it's a markdown link.

**Comment by dnmfarrell** [comment]
I can fix the shortcode and the current instances of it, if you agree ^

**Comment by briandfoy** [comment]
I'm fine but I just made a bunch of commits. Anything to make it so we can change the link later.

**Comment by briandfoy** [comment]
I'll clean all this up right now.

**Comment by briandfoy** [comment]
Looking back on this I should have done all this in a branch and squashed it. I cleaned up the ones I did today under _legacy/_

**Comment by briandfoy** [comment]
The mcpan short code now only expands to a URL and I've looked at every use of it to ensure it shows up in a markdown link.

**Comment by briandfoy** [comment]
I think I've fixed all of these. If we find more let's open new tickets for those articles.
