### ISSUE TITLE
Article needed: Perl foreach tutorial

### ISSUE THREAD

**Issue by dnmfarrell** [tpf/perldotcom#133]
We have:
https://www.perl.com/doc/FMTEYEWTK/style/slide22.html/
https://www.perl.com/article/11/2013/4/4/Perl-arrays-101---create--loop-and-manipulate/

But neither are highly ranked on Google. Let's create one specifically about "foreach" loops.

**Comment by briandfoy** [comment]
I have a draft article in briandfoy/133-foreach-article

**Comment by briandfoy** [comment]
I've proofed this article and I think it's ready for the final polish. It needs an image.

**Comment by dnmfarrell** [comment]
I've edited the article in the branch. One thing I think we should touch upon is control directives.

This could be as simple as a link to http://perldoc.perl.org/perlsyn.html#Loop-Control

What do you think?

**Comment by briandfoy** [comment]
I added simple examples of the loop controls and linked to the docs.

**Comment by dnmfarrell** [comment]
Merged and published. This is live! thanks @briandfoy :+1: 
https://www.perl.com/article/perl-foreach-loops/

**Comment by mohawk2** [comment]
It looks (since I tried to use this as an example of the "open a PR" link) like the file got renamed from `.../perl-foreach-loops.md` to `.../perl-for-loops.md` after the site got generated/deployed?

Also, if it's published, this issue could be closed?

**Comment by briandfoy** [comment]
It looks like GitHub does not have to latest commits. The _.../perl-for-loops.md_ article is a different one by Tom C.

**Comment by dnmfarrell** [comment]
I published the article but didn't push the merged commits, they're pushed now. The article is called `content/article/perl-foreach-loops.md`. The other article, `perl-for-loops.md` is an old PerlTricks article I wrote ages ago.
