### ISSUE TITLE
Article needed: how to download Perl

### ISSUE THREAD

**Issue by dnmfarrell** [tpf/perldotcom#136]
We need a simple article on how to download Perl. It should cover:
- Downloading and installing pre-compiled binaries for popular operating systems
- Downloading and building Perl from source and installing to custom locations

**Comment by mjgardner** [comment]
I'd like to work on this. Would you mind assigning it to me?

**Comment by dnmfarrell** [comment]
Thanks @mjgardner! Our [contributing doc](https://github.com/tpf/perldotcom/blob/master/CONTRIBUTING.md) can help you get started.

**Comment by mjgardner** [comment]
Can this be closed, or does it wait until the article is published?
