### ISSUE TITLE
Article needed: CGI and Perl

### ISSUE THREAD

**Issue by dnmfarrell** [tpf/perldotcom#138]
We need an article that discusses CGI in a modern context. It should cover:
- How to create a simple web app with CGI
- Recommend CGI resources (Lincoln Stein's book was pretty good from what I remember)
- Why CGI is not recommended
- CGI alternatives (Plack, Dancer, Mojolicious)

We already have:
- https://www.perl.com/pub/2000/12/begperl4.html/

**Comment by jacoby** [comment]
I have a first-pass at this.

To what extent are you wanting content on Plack, Dancer, Mojolicious?

**Comment by dnmfarrell** [comment]
Thanks @jacoby !

I think all that's required for those is a one sentence description with a link to the metacpan distribution.

**Comment by dnmfarrell** [comment]
This is live! https://www.perl.com/article/perl-and-cgi/

**Comment by leejo** [comment]
My thoughts: https://www.reddit.com/r/perl/comments/9wfgtf/perl_and_cgi/e9pfl07/

**Comment by delgreco** [comment]
I realized my question might be better on SO:
https://stackoverflow.com/questions/53339936/should-i-migrate-from-cgifast-to-something-else-in-light-of-cgi-pms-deprecate

**Comment by dnmfarrell** [comment]
@leejo Thanks for the feedback. I've pushed a change 0d47f6482163c511cae7375ed649fef83af1f3a9 which tries to incorporate it.
