### ISSUE TITLE
Links from Google search results lead to 404

### ISSUE THREAD

**Issue by spidamoo** [tpf/perldotcom#141]
Google still shows search.cpan.prg pages in its search result. Those now redirect to metacpan, but not to something that you would end up seeing if use metacpan search, but something like https://fastapi.metacpan.org/source/Dancer2/lib/Dancer2/Session/YAML.pm which in turn displays a 404 error.

**Comment by dnmfarrell** [comment]
@spidamoo thanks for the info, though I'm not sure there's anything we can do about it?

**Comment by spidamoo** [comment]
@dnmfarrell I'm not sure if this is a part of this project or not (I assumed it is because a link on metacpan saying "this is now going to replace search.cpan.org" leads here) but what we could do is to change the logic that decides to which exact metacpan page to redirect on search.cpan.org and make it redirect to the main module page (in example that I gave that would be https://metacpan.org/pod/Dancer2::Session::YAML)

**Comment by dnmfarrell** [comment]
Oh I see what you mean, because Olaf wrote the article about the change on Perl.com, and it's linked from metacpan.org. @oalders any idea who to speak to on search.cpan.org about this?

**Comment by oalders** [comment]
@haarg do we have an open issue for this one?

**Comment by haarg** [comment]
This should be working correctly now.
