### ISSUE TITLE
Let's run a promotion for Hacktoberfest

### ISSUE THREAD

**Issue by briandfoy** [tpf/perldotcom#146]
We need some ways for people to submit pull requests as part of Hacktoberfest: https://hacktoberfest.digitalocean.com

**Comment by Leont** [comment]
Seems like a fine idea

**Comment by dnmfarrell** [comment]
I'll write an article for this. Once it's live perhaps we can add a Hacktoberfest banner that directs to the article.

**Comment by dnmfarrell** [comment]
Ok @briandfoy article is [done](https://www.perl.com/article/support-perl-com-and-get-a-free-t-shirt-with-hacktoberfest/), and banner is live

**Comment by briandfoy** [comment]
Looks good. Thanks,
