### ISSUE TITLE
Make Readme.md Better

### ISSUE THREAD

**Issue by D3v3sh5ingh** [tpf/perldotcom#150]
- Company logo could be added.

- More better explanation.

- More about the perl.com.

**Comment by dnmfarrell** [comment]
Hi @D3v3sh5ingh 

We don't have a company logo but was there something you were expecting to find in the readme that was missing?

**Comment by D3v3sh5ingh** [comment]
It would be better if we add more about what organisation do and what's its aim because this is the main repository of the perl foundation.

**Comment by dnmfarrell** [comment]
Gotcha.

This repo contains the source code for Perl.com, a website for publishing articles about Perl and Open Source. It's not The Perl Foundation's (TPF) website, but but it's *managed* by TPF. We do already include a link to TPF's website in the readme.

I'd rather keep content about TPF on their website and content about Perl.com (such as how to contribute an article etc) in this repo, just as I don't expect TPF's website to describe what Perl.com is all about, only to link to us as an affiliate.

That way if TPF update their content, we don't have to worry about updating any TPF content on Perl.com and vice versa.

I hope that makes sense @D3v3sh5ingh !
