### ISSUE TITLE
Missing metadata key in file "about.md" to confirm

### ISSUE THREAD

**Issue by sdeseille** [tpf/perldotcom#162]
Hello

In working on issue #82 i got an error with my code.
I found that metadata keys "tags" and "authors" are missing in file "about.md".
Some others keys are missing.

Here you can see the current metadata: 

{
  "title": "About Perl.com",
  "type": "about",
  "categories": "meta"
}

Is it normal ? If not i propose to compose metadata like this:
{
    "title"       : "About Perl.com",
    "authors"     : ["david-farrell"],
    "date"        : "",
    "tags"        : ["about"],
    "draft"       : false,
    "image"       : "",
    "thumbnail"   : "",
    "description" : "",
    "categories"  : "meta"
}

What do you think ?

regards

**Comment by briandfoy** [comment]
Ignore the about.md file. It's not a normal article.

**Comment by sdeseille** [comment]
Ok thanks.

Regards

Le jeu. 11 oct. 2018 à 17:14, brian d foy <notifications@github.com> a
écrit :
