### ISSUE TITLE
Let's clean up old git branches

### ISSUE THREAD

**Issue by briandfoy** [tpf/perldotcom#164]
I think many of the branches can be deleted. If they are merged we don't need them and if they aren't, maybe we forgot to do something. I've cleaned up the ones I created and don't need any more.

I don't think these came from me:

- [ ] dfarrell/edit-cpan-contributor-2
- [ ] dnmfarrell/require-return-false
- [ ] intro-article-updates
- [ ] kivanc-setup-computer-cpan-prc
- [ ] kyzn-why-join-prc
- [ ] olaf-alders/saying-goodbye-to-search-cpan-org
- [ ] remove-authors-from-tags
- [ ] review-how-to-become-cpan-contributor
- [ ] sawyer-smartmatch
- [ ] tpc-teaser

These are active for things I'm doing

	briandfoy/makefile
	briandfoy/new_article_prompt
	briandfoy/python
	briandfoy/term-ansicolor

**Comment by dnmfarrell** [comment]
done!
