### ISSUE TITLE
Article request: compile-time programming in C++ and Perl

### ISSUE THREAD

**Issue by cxw42** [tpf/perldotcom#175]
I just read this in [Herb Sutter's latest report](https://herbsutter.com/2018/11/13/trip-report-fall-iso-c-standards-meeting-san-diego/):

> C++ is serious about first-class compile-time programming. ... We’re on track to making most “normal” C++ code available to run at compile time ...

Sounds like BEGIN! :)

Would someone who's current on C++17/C++20 be willing to write an article comparing Perl (or 6lang (since I don't know what to call it now) or both) to C++ in this regard?

Thanks for considering this request!

**Comment by Leont** [comment]
I'm current on both C++ and Perl, in this regard they're so different that I don't think one can really compare them. In Perl one can do almost anything at compile time, in C++ much less so (mainly by lack of dynamic allocation, and lack of something similar to our stash)

**Comment by cxw42** [comment]
@Leont OK - thanks for the info!

**Comment by cxw42** [comment]
Closing as no one else has chipped in.
