### ISSUE TITLE
Move https://github.com/mohawk2/perlsphere under tpf?

### ISSUE THREAD

**Issue by mohawk2** [tpf/perldotcom#178]
Sorry, this may not be right place to raise this. I note that perldotcom now lives under tpf. I've just taken over "perlsphere" and it seems to me it would be better off under the "tpf" umbrella, albeit with me responsible in the normal way of things.

How would one go about this?

**Comment by dnmfarrell** [comment]
Hi @mohawk2 

I would email Jim Brandt ("jim at perlfoundation dot org") to discuss it.

**Comment by mohawk2** [comment]
I will, thanks!
