### ISSUE TITLE
Comment on fork blog entry

### ISSUE THREAD

**Issue by matthewpersico** [tpf/perldotcom#186]
I didn't see a place to ask questions or log in (maybe I'm just blind), so here it is:

>If you’re not worried about fork failing, I recommend using Parallel::ForkManager, ...

I don't understand the comment; does `Parallel::ForkManager` not handle failed forks well?

**Comment by dnmfarrell** [comment]
hey @matthewpersico I'm glad you asked that, I responded on the perl subreddit [thread](https://www.reddit.com/r/perl/comments/b8d9db/fork_yeah/)
