### ISSUE TITLE
Links between articles-in-parts missing?

### ISSUE THREAD

**Issue by akarelas** [tpf/perldotcom#193]
Shouldn't there be a link from this article: https://www.perl.com/article/fork-yeah-/ to this article: https://www.perl.com/article/fork-yeah-part-2/ ?

Shouldn't such links be added automatically when new parts are added?

**Comment by dnmfarrell** [comment]
We could create a frontmatter attribute which links articles in a series, but I'm not sure how it would be done automatically. What do you think?

**Comment by dnmfarrell** [comment]
@akarelas did you have any more thoughts on this issue?
