### ISSUE TITLE
Article subheadings style guide mismatch

### ISSUE THREAD

**Issue by oalders** [tpf/perldotcom#195]
From https://www.perl.com/article/how-to-write-your-first-article-for-perl-com/

Article subheadings are size h3. So use the following construct:

`### Subtitle goes here`

From https://github.com/tpf/perldotcom/blob/master/STYLE-GUIDE.md

Use header 2 for subtitles, with the dash style:

```
Foo Bar
-------
```

**Comment by dnmfarrell** [comment]
Thanks for reporting this, I've pushed a fix and will deploy it shortly.

**Comment by oalders** [comment]
T
