### ISSUE TITLE
article on "quoting the shell" shoud mention system(@cmd_args)

### ISSUE THREAD

**Issue by marekro** [tpf/perldotcom#201]
The article: https://github.com/tpf/perldotcom/blob/master/content/article/quoting-the-shell.md
is excellent - IMHO, to make it complete, I propose to add a paragraph on the array form of system(), i.e.
    system('tag', $file);
and then expand on the problem that this doesn't capture the output. Which leads us to the three (and more) argument form of open():
    open(IN, '-|', 'tag', $file);
Since no shell is in between, there is no issue with quoting either. Alas, we don't capture STDERR here... so in order to use native Perl (= not a module), we may need to say:
    my $pid = open(IN, '-|'); # a child to read from
    unless(defined $pid) {
      die "Cannot fork: $!\n";
    }
    elsif($pid == 0) { # child process
      open(STDERR, '>&', \*STDOUT) or die "Cannot redirect STDERR to STDOUT: $!\n);
      # the array form of exec() doesn't require quoting
      exec('tag', $file) or die "Cannot exec 'tag $file': $!\n";
    }
    # parent
    while(<IN>) {
      print; # here we can also process the output
    }
    close(IN);
    # and here we have the command's exit status in $?

I get your point that all that should be "simpler", like supported by native Perl, but I think there is also room for modules :)

**Comment by dnmfarrell** [comment]
Hey thanks for opening this issue and providing a suggested fix. Let me have a think about it and get back to you.

**Comment by briandfoy** [comment]
I write about this in Mastering Perl and it's a bit more complicated (not much). I can add something like this though.

**Comment by briandfoy** [comment]
Dome in 2c200767cba86656b9053cde1cd26ef8dfb77576. Thanks!
