### ISSUE TITLE
Feature your project in Hacktoberfest on Perl.com

### ISSUE THREAD

**Issue by briandfoy** [tpf/perldotcom#203]
[Hacktoberfest](https://hacktoberfest.digitalocean.com) is coming up and I'll write an article to highlight that.

Would you like your project to be part of my article? Leave a comment in this issues.

For me, there are various things I'd like to fix up with [PerlPowerTools](https://metacpan.org/pod/PerlPowerTools). There are some [style issues noted in kritika.io](https://kritika.io/users/briandfoy/repos/7253941177493998/) that should be easy ways to contribute and learn the GitHub system.

**Comment by jmacdotorg** [comment]
Howdy brian,

I've released a couple of new projects this summer & fall:

[Web::NewsAPI](https://metacpan.org/pod/Web::NewsAPI) is a module for communicating with NewsAPI, letting you fetch and search news headlines and stories from around the world using Perl.

[Sweat](https://metacpan.org/pod/distribution/Sweat/script/sweat) is a fully-featured workout timer that aims to distract you from the pain of exercise by reading mildly interesting stuff from the internet. It's pretty ridiculous and I have been using it every day for weeks. It's been on CPAN for only the past week or so, and [I just published a blog post about it](https://fogknife.com/2019-09-16-announcing-sweat-a-flexible-and-distracting-workout-timer.html).

**Comment by kyzn** [comment]
Hi Brian! I built [Pull Request Club](https://pullrequest.club) about 10 months ago to be a successor to CPAN Pull Request Challange. Today we have 78 members, but only 13 people are opted in to have their repositories assigned to other people. On the other side, we have 52 people opted in to receive assignments. Which is to say, we need more repositories :)

I would be honored if Pull Request Club was introduced to more people as a way of getting pull requests to their projects.

**Comment by briandfoy** [comment]
> I would be honored if Pull Request Club was introduced to more people as a way of getting pull requests to their projects.

Wow, that looks really cool. Thanks!

**Comment by frankiejol** [comment]
I work in this project made in Perl, we always have nice contributions on hacktoberfest, but most of them are translations. We will try to add some *good first issue* issues.
https://github.com/UPC/ravada

**Comment by Difegue** [comment]
Hey there brian, 
I work on a self-hosted comic/manga manager running on Mojo, it's been picking up a bit of steam recently and I just tagged a bunch of issues for newcomers/hacktoberfest. 😀
https://github.com/Difegue/LANraragi

**Comment by cxw42** [comment]
I've only tagged one so far, in https://github.com/cxw42/Class-Tiny-ConstrainedAccessor .  I'm hoping to tag a few more in other repos over the next few days.  Thanks for putting the article together!

**Comment by mienaikage** [comment]
Tweaks/improvements/new exercises would be welcome on https://github.com/exercism/perl5 and https://github.com/exercism/perl6 for https://exercism.io. I need to make some improvements to the contributing docs myself.

**Comment by djzort** [comment]
An ambitious person might like to create a PSGI layer for HTTP::Tiny. 

See also https://github.com/perl-gsoc-2019/ideas/issues/34 and https://github.com/chansen/p5-http-tiny/issues/130

**Comment by cxw42** [comment]
@briandfoy I added a bunch to https://github.com/cxw42/git-find .  Thanks!

**Comment by djzort** [comment]
Supporting markdown on metacpan would be very handy, see https://github.com/metacpan/metacpan-web/issues/2191

**Comment by oalders** [comment]
@kyzn I belong to the libwww-perl GitHub org.  How could I make those repositories available for assignment via your site?

**Comment by kyzn** [comment]
@oalders That's a great point.. Unfortunately I couldn't get to implement support for organization-repos yet. If you can point me to the repos you want to add, I can do so manually for the time being (and we can do it the right way once the implementation is done). Would that work for you?
