### ISSUE TITLE
Dead link in _pub_2005_11_17_handel.md

### ISSUE THREAD

**Issue by Williams-Dan** [tpf/perldotcom#213]
In content/legacy/_pub_2005_11_17_handel.md there is a link to a sql script for building the sqlite3 schema, this link is dead, can we perhaps replace it or updated the file with the correct sql?

**Comment by dnmfarrell** [comment]
Thanks for reporting this. I found the file on CPAN:
https://fastapi.metacpan.org/source/CLACO/Handel-1.00014/sql/handel.sqlite.sql

I've updated the article, the site should be fixed in the next 20 minutes.

**Comment by dnmfarrell** [comment]
The link is working again.
