### ISSUE TITLE
Any interest in Dancer2/DBIC/HFH/... content?

### ISSUE THREAD

**Issue by cxw42** [tpf/perldotcom#215]
Lately I have been learning Dancer2, DBIx::Class, and HTML::FormHandler.  I am today porting Dancer::Plugin::MobileDevice to Dancer2 (**edit** [here](https://github.com/cxw42/Dancer2-Plugin-MobileDevice)).  Would you have any interest in articles about getting started with any of those packages?  There are some existing blog posts, and Gabor has an [ebook](https://leanpub.com/dancer-spa), but I haven't seen much recent material.  Pleast let me know either way.  Thanks!

(By the way, I haven't forgotten part 2 of #210 on my list.  I need to retest with the new, refactored toke.c before I can work on that.)

**Comment by dnmfarrell** [comment]
hey @cxw42 , sure those sound like interesting topics!

**Comment by cxw42** [comment]
Starting to work on an article, so I'm going to close this.  Thanks!
