### ISSUE TITLE
Request: option for author-specific "browse <foo> articles" link text

### ISSUE THREAD

**Issue by cxw42** [tpf/perldotcom#216]
First, some disclaimers:

- I am not trying to step on anyone's toes.
- I don't want to force anyone to do anything.
- I am not an expert in language usage.
- I am not setting any deadlines.
- I am not complaining.
- I am not sure I should be opening this issue at all!

With that out of the way, a request: would it be possible for links to https://www.perl.com/authors/christopher-white to say "Browse his articles" rather than "Browse their articles"?  E.g., on <https://www.perl.com/article/my-perl-wishlist-invariant-sigils-part-1/>:

![image](https://user-images.githubusercontent.com/10515894/71547726-c87e8700-2971-11ea-8cda-aa67893cd9f4.png)

I sometimes find singular-"they" confusing, and there's only one of me :D .  Since Hugo is pulling from the author metadata, I think this might be a one-line change from:

https://github.com/tpf/perldotcom/blob/613320695ec18ceac55d4121e4f647d0ba86cee3/layouts/partials/author.html#L10

to:

    <h5><a href="/authors/{{ $author.key }}">Browse {{ (or $author.their "their") | html }} articles</a></h5>

(but I've never used Hugo, so I could well be wrong!).

If that is indeed the case, I would be happy to submit a PR.  Please let me know what you think.  Thanks!

**Comment by dnmfarrell** [comment]
Hey Chris,
Great idea, I like it a lot. Your proposed code looks good to me at a cursory glance. Do you want to submit that PR?

Thanks

**Comment by cxw42** [comment]
David, thanks for responding and approving!  Sure, I'll open the PR.  It will be a few days since I will need to test it and haven't had to install Hugo before now :D .

BTW Statocles or [wallflower](https://metacpan.org/pod/distribution/App-Wallflower/bin/wallflower)? ;)

**Comment by cxw42** [comment]
@dnmfarrell By the way, re. my comment about static site generators, https://github.com/cxw42/unbelievable :D .  I got inspired, and the world doesn't have enough site generators already ;) .  In four hours (I timed it) I was able to hook up Dancer2 with wallflower, and add shortcodes!
