### ISSUE TITLE
Ordering matters in alternate matching?

### ISSUE THREAD

**Issue by Siddhant** [tpf/perldotcom#218]
This in reference to "content/article/perl-6-grammers-part-1.md" ([Perl 6 Grammars, Part 1](https://www.perl.com/article/perl-6-grammers-part-1/))

Instead of the given order:
```
token value {
    | <digits> '.' <digits>
    | '.' <digits>
    | <digits> '.'
    | <digits>
}
```
I defined a different order:
```
token value {    
    | <digits> '.' <digits>
    | <digits>
    | '.' <digits>
    | <digits> '.'
}
```

And it did not work with some values, like "3." 

I was under the assumption that the ordering of the 4 variations would not matter.
What am I missing ? 

```
C:\Users\Siddhant\perl6>perl6 --version
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```

**Comment by cxw42** [comment]
@Siddhant Good question!  You might have better luck asking at some of the forums listed on https://raku.org/community/ .  Other resources are listed at https://raku.org/resources/ .  (raku.org because Perl 6 has been renamed to "Raku".)  If you find out, please let us know! :)
