### ISSUE TITLE
Rock Pi S Review - really get A1 sd card?

### ISSUE THREAD

**Issue by p-bo** [tpf/perldotcom#222]
So get an A1 card and you’ll be happy with the results.
Shouldn't it be A2 card?                                                                              

According mentioned
https://www.sdcard.org/developers/overview/application/index.html
A2 class is lot more iops...

**Comment by dnmfarrell** [comment]
@frezik do you know this answer to this question?

**Comment by frezik** [comment]
It depends on the bandwidth of the card connection. On the Raspberry Pi 3 and earlier, the connection was bottlenecked by the CPU, so an A2 card made no difference. There were a lot of improvements on the bandwidth for the Pi4, though I haven't looked into benchmarks for the SD card performance. The Rock Pi S, of course, is a different beast entirely.

What I can say is that having at least an A1 improves things quite a bit.
