### ISSUE TITLE
BloomFilter_wrap.cxx:763:20: fatal error: EXTERN.h: No such file or directory

### ISSUE THREAD

**Issue by bioramg** [tpf/perldotcom#229]
Hi,
I am trying to install LINKS. Before that, I have followed your instructions and trying to build a perl5 module and getting an error while running the command:
g++ -c BloomFilter_wrap.cxx -I/usr/lib64/perl5/CORE -fPIC -Dbool=char -O3

Error: BloomFilter_wrap.cxx:763:20: fatal error: EXTERN.h: No such file or directory

So, what shall I do? I already checked in my computer. Perl5 is installed and could not find CORE folder in /usr/lib/perl5/ and also there is no Perl in /usr/lib64/

Please help to sort out this issue. Thank you.

**Comment by briandfoy** [comment]
It looks like you need to install the Perl development packages because this is missing a header file. StackOverflow might be a good place for support.
