### ISSUE TITLE
Glyphs not displaying on 2015 "Introducing 3 new Perl Glyphs" article...

### ISSUE THREAD

**Issue by jubilatious1** [tpf/perldotcom#233]
https://github.com/tpf/perldotcom/blob/master/content/article/introducing-3-new-perl-glyphs.md

Viewing the page with the latest Firefox I see the following text, not glyphs:

> First a couple of Perl 5 classics, colored:
> 
> image/svg+xml
> 
> image/svg+xml
> 
> And a black-and-white Camelia for Perl 6:
> 
> image/svg+xml
> 
> Of course, being svg you can color them however you like.

**Comment by dnmfarrell** [comment]
Thanks for reporting this. They're baaaaack!

https://www.perl.com/article/146/2015/1/23/Introducing-3-new-Perl-Glyphs/
