### ISSUE TITLE
Left margin is too narrow on iOS 

### ISSUE THREAD

**Issue by thibaultduponchelle** [tpf/perldotcom#243]
Hello,

There is a problem with left margin on iOS, it is too narrow.

It's not pleasant for reading.

![margins](https://user-images.githubusercontent.com/580360/84248110-42ae5c80-ab09-11ea-874c-0c2e01f85b3a.png)

Thibault

**Comment by briandfoy** [comment]
On my device, there is *no* margin. That certainly is unpleasant. What's worse is I can't use Reader Mode on this.

**Comment by abh** [comment]
Fwiw, reader mode does seem to work for the articles on the iOS 14 beta.

**Comment by thibaultduponchelle** [comment]
Thank you a lot, I checked and it's good now :+1:
