### ISSUE TITLE
youtube video for SOTO 2000

### ISSUE THREAD

**Issue by toddr** [tpf/perldotcom#245]
Hi, I'm just letting you know that I created a YouTube video for Larry's [SOTO in 2000](https://www.perl.com/pub/2000/10/23/soto2000.html/). The youtube video is in the yapcna channel and can be found here. https://youtu.be/a1SEt_-QMDo 

Please let me know if you have any questions or concerns.

Todd

**Comment by briandfoy** [comment]
Added in 14fa78ab7216e37b526636ee4f8118b16670264d and will be part of the next site refresh.
