### ISSUE TITLE
Missing link in Ovid article

### ISSUE THREAD

**Issue by Ovid** [tpf/perldotcom#266]
For this article [The Perl Ambassador: Curtis 'Ovid' Poe](https://www.perl.com/article/the-perl-ambassador-curtis-poe/) (https://github.com/tpf/perldotcom/blob/master/content/article/the-perl-ambassador-curtis-poe.md), the sentence "Here’s the case study of that project." should be a link to this case study: https://ovid.github.io/articles/project-500.html

And thanks for the kind words in the article.

**Comment by dnmfarrell** [comment]
Thanks for reporting this Ovid, I'll fix it now.

**Comment by dnmfarrell** [comment]
This is live, you might have to clear browser cache to see the changes reflected.
