### ISSUE TITLE
Do you forget something here?

### ISSUE THREAD

**Issue by KES777** [tpf/perldotcom#281]
![image](https://user-images.githubusercontent.com/799021/95857975-0ca61100-0d65-11eb-8edc-ab7bb768db92.png)

https://www.perl.com/article/182/2015/7/15/Stupid-open-tricks/

**Comment by briandfoy** [comment]
This is fixed in 759c75fc and will be part of the next refresh. Thanks!

**Comment by KES777** [comment]
thank you too
