### ISSUE TITLE
binmode and UTF-8

### ISSUE THREAD

**Issue by taniwallach** [tpf/perldotcom#283]
In https://www.perl.com/pub/2012/04/perlunicook-decode-standard-filehandles-as-utf-8.html/  I think you may want to use 
```
binmode(STDOUT, ":encoding(UTF-8)");
```
instead of
```
binmode(STDOUT, ":utf8");
```
as Perl 5.30 is making it fatal to `sysread` and `syswrite` on `:utf8` filehandles (it was deprecated in 5.24), which apparently can occur when `binmode` is set to `:utf8`.

Same for the similar lines for `STDIN` and `STDERR`.

See: https://perldoc.perl.org/perl5300delta#Previously-deprecated-sysread()/syswrite()-on-:utf8-handles-is-now-fatal

**Comment by briandfoy** [comment]
This is updated in 9d2992ed and will be part of the next refresh. Thanks!

**Comment by taniwallach** [comment]
Thanks for the fast handling and making the update.
