### ISSUE TITLE
Mojolicious O'Reilly scraper: needs more exposure

### ISSUE THREAD

**Issue by matthewpersico** [tpf/perldotcom#296]
Brilliant. That's the kind of quick and easy tutorial that newbies (an a non-webber oldie like me) need. But putting it ONLY on Perl.com is living in the echo chamber. I'm sure it will end up being linked too on reddit but maybe a link on someplace lie dev.io would also be in order?

**Comment by briandfoy** [comment]
Glad you liked it!

Plaster it all over the place if you like. I think I originally mentioned it in /r/programmer. I'm only ever going to publish my articles in one place. 

dev.io looks like someone's personal blog, but I'm open to publishing articles in any place that will have me.
