### ISSUE TITLE
stupid data tricks error

### ISSUE THREAD

**Issue by rubysash** [tpf/perldotcom#297]
https://www.perl.com/article/stupid-data-tricks/

great article!   1 error:

#!/usr/bin/perl
use v5.26;
use Text::CSV_XS;

my $csv = Text::CSV_XS->new;
while( my $row = $csv->getline(*DATA) ) {
	say join ':', $row->@[3,7];
    }
close $fh;

no open $fh

**Comment by briandfoy** [comment]
Fixed in 95d44781e96b09626d7ea0e42c2d367879843e8f. Thanks!
