### ISSUE TITLE
Replacing hardcoded perl.com links temporarily?

### ISSUE THREAD

**Issue by kyzn** [tpf/perldotcom#299]
Hi! Thanks for keeping perl.com alive.

I just saw the news that perldotcom.perl.org is the temporary new address. Would you like a PR that replaces all hardcoded `perl.com`s with the temporary address in one commit? Once the domain is recovered we should be able to revert the commit. If that sounds useful I can spend some time on it.

Or maybe we can replace those with `relref`? That may be a better solution.

Thanks!

**Comment by briandfoy** [comment]
I think I got most of those in db253f6821d443ba9398664bbeae1b90c5060352, but if you find more, send a pull request. Thanks!
