### ISSUE TITLE
Re-org repo

### ISSUE THREAD

**Issue by dnmfarrell** [tpf/perldotcom#30]
This repo should be moved to the Perl organization, and the tpf.github.io
submodule removed. Additionally the perl.com directory should be deleted
as it duplicates many files, including several large media files.

**Comment by dnmfarrell** [comment]
@cbrandtbuffalo could you create a `perl.com` repo in the TPF org and add me and briandfoy as collaborators please?

I think a fresh repo is a better option than a transfer as this one's commit history contains all the legacy files being added and deleted, including some large media files. Plus a transfer would require us to get the timing right, e.g. once the repo is moved we'd need to update the site immediately or else the links will be broken. Once the new repo is created we can:

* Copy the repo files into it
* Transfer any open issues
* Make sure the repo is public
* Update the repo path in `config.toml`, and re-generate the site which will update the links all over the site
* Test the links work - header, footer and an article "raise an issue on github" link
* Deploy the site

**Comment by dnmfarrell** [comment]
I've changed my mind. Now we're rolling with many issues, and contributions from other authors, I think we're better off transferring the repo at some point.

**Comment by cbrandtbuffalo** [comment]
OK, let me know how you want to move forward with that and we can work on timing and the proper rights for the repo after the transfer.

**Comment by dnmfarrell** [comment]
Hi @cbrandtbuffalo, can you give me the owner role in the tpf organization please? I tried to open a transfer but GitHub won't let me unless unless I have permission to create repos under tpf.

**Comment by dnmfarrell** [comment]
We did this, we're now under the TPF org. Go us!
