### ISSUE TITLE
Sidebar link to "The Trouble with Reference Counting" links to perl.com

### ISSUE THREAD

**Issue by raiph** [tpf/perldotcom#305]
# Expected

All direct links from the new perldotcom.perl.org home page that were to perl.com would now instead be to perldotcom.perl.org.

# Actual

The LATEST COMMUNITY ARTICLES sidebar
The Trouble with Reference Counting
links to https://www.perl.com/article/the-trouble-with-reference-counting/

# Comments

In https://www.reddit.com/r/perl/comments/l7bwn5/perldotcomperlorg_is_a_temporary_host_for_perlcom/gl85hun/ briandfoy says "To me, things look as they should be.".

Although I don't see why it would make a difference, I cleared my browser's file cache just in case. It didn't fix the problem.

# System info

Windows 10
Version 2004
Installed on 04/11/2020
OS build 19041.746
Experience 120.2212.551.0

Google Chrome
Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by briandfoy** [comment]
There are a couple things going on here:

- [ ] PerlyBot has the old links in [https://s3.amazonaws.com/perly-bot.org/links.json](https://s3.amazonaws.com/perly-bot.org/links.json)
- [ ] The toplinks.js excludes links whose host matches the current page host, which means you can see different things depending on the URL host

**Comment by briandfoy** [comment]
This is fixed in 35b90f91ef4322fe645ef4afb53e9f5c4a6f8cb2, which is live now.
