### ISSUE TITLE
/article/index.xml contains href links to perl.com

### ISSUE THREAD

**Issue by raiph** [tpf/perldotcom#306]
# Expected

Links from /article/index.xml (linked from several places on the perldotcom.perl.org home page, eg a button in the MORE: section at top right) that were to perl.com would now either warn or link to perldotcom.perl.org instead of perl.com.

# Actual

The xml I got as of 1st Feb 2021 is in [this GH gist](https://gist.github.com/raiph/ef984ab2218c7f5ec57bf36ab5ff65fa).

If you search it you should see it contains 3 href links to www.perl.com/....

# Comments

In https://www.reddit.com/r/perl/comments/l7bwn5/perldotcomperlorg_is_a_temporary_host_for_perlcom/gl85hun/ briandfoy says "To me, things look as they should be.".

Although I don't see why it would make a difference, I cleared my browser's file cache just in case. It didn't fix the problem.

# System info

Windows 10
Version 2004
Installed on 04/11/2020
OS build 19041.746
Experience 120.2212.551.0

Google Chrome
Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by briandfoy** [comment]
I don't see any perl.com links your gist output. There is the site title "Perl.com", but those aren't links. We're considering what to do with the branding, but that's blocked by a few things at the moment.

**Comment by raiph** [comment]
Hi @briandfoy,

> I don't see any perl.com links your gist output.

Did you click Raw and search for 'perl.com' or just look? Did you see, for example:

> previously written about <a href="https://www.perl.com/article/182/2015/7/15/Stupid-open-tricks/">Stupid Open Tricks</a>

?

That might not be a problem, but it's one of the 3 I said were hrefs, and if it's part of a title, well, it still looks to me like it'll be clickable.

**Comment by briandfoy** [comment]
I looked at the gist and didn't bother to look at the raw. This is why I've asked you before to be very specific. If I have to dig for buried treasure that you've already found, you aren't making the best report that you can make.

**Comment by briandfoy** [comment]
The feed stuff has solved itself when we redeployed the site earlier today. The resource at https://perldotcom.perl.org/ now uses the new base URL.
