### ISSUE TITLE
Search DuckDuckGo with current host

### ISSUE THREAD

**Issue by raiph** [tpf/perldotcom#307]
# Expected

Using search field at top of perldotcom.perl.org, which searches via duckduckgo, would be disabled (or direct duckduckgo, or some other search engine, to search with "site:perldotcom.org" if that search engine has already mapped perl.com to perldotcom.org, or indexed it, or some other solution that avoids perl.com for now).

# Actual

I get duckduckgo search results using "site:perl.com".

# Comments

Although I don't see why it would make a difference, I cleared my browser's file cache just in case. It didn't fix the problem.

# System info

Windows 10
Version 2004
Installed on 04/11/2020
OS build 19041.746
Experience 120.2212.551.0

Google Chrome
Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by briandfoy** [comment]
This is hardcoded into _layouts/partials/header.html_, so we'll have to update that

**Comment by briandfoy** [comment]
Two things to do:

- [ ] Immediate response to change hardcoded value
- [ ] Long term response to take host from config

**Comment by briandfoy** [comment]
This will be part of the next site update, which should happen shortly.
