### ISSUE TITLE
minor nits with "Perl 6 Grammars, Part 1"

### ISSUE THREAD

**Issue by RichMorin** [tpf/perldotcom#339]
This is a very nice intro, but I noticed some minor nits.

The URL has a typo which might be confusing:

    https://www.perl.com/article/perl-6-grammers-part-1/#author-bio-andrew-shitov
    ---
    https://www.perl.com/article/perl-6-grammars-part-1/#author-bio-andrew-shitov

"builtin" should be changed to "built-in".

There is a missing conjunction:

    ... notation, special forms ...
    ---
    ... notation, and special forms ...

The first code example will not produce the depicted result. Perhaps it should be extended:

    for <1 42 123 1000> -> $n {
    ---
    for <1 42 123 1000 -3> -> $n {

This comma seems to be superfluous:

    ... Also notice, that ...
    ---
    ... Also notice that ...

I would rewrite this as follows:

    ... for the floating point.
    ---
    ... for floating point numbers.

"ad hoc" should probably be italicized.

I would rewrite "can be creating" as "might create".

I would split up this sentence:

    ... wrong, as, for example ...
    ---
    ... wrong. For example ...

I would rewrite this sentence a bit:

    ... digits and works ...
    ---
    ... digits, it works ...

I would change "All works fine." to "This all works fine."

"hex, binary and octal" should be "hex, binary, and octal"

**Comment by briandfoy** [comment]
Fixed, thanks.

Next time, this sort of issue would be easy to apply as a pull request.

**Comment by RichMorin** [comment]
Thanks for applying the changes.  I refrained from creating a patch and pull request because some of the changes were matters of taste, etc.
