### ISSUE TITLE
Consider a transfer of this repo to https://github.com/perladvent

### ISSUE THREAD

**Issue by oalders** [tpf/perldotcom#342]
Regarding the comments at https://github.com/tpf/perldotcom/pull/331#issuecomment-1366698556

What I think we could do is move this repo to https://github.com/perladvent which has one core competency (publishing Perl blog posts).

> the domain belongs to tchrist, and TPF can use it.

👍🏻 

> the Perl NOC handles a lot of the details. This site uses Hugo to write to a different repo, and the Perl NOC setup publishes that second repo to Perl.com

I think that we can move the publishing to a 3rd party like render.com (which has live previews for pull requests) or even just publish via GitHub pages. That would make publishing immediate and eliminate the need to maintain infrastructure just for this site.

If we can get a sign-off on something like this, we'd could transfer the repo, get the Hugo deploy up and running and then, as a last step, ask for the DNS servers to be changed.

**Comment by briandfoy** [comment]
I don't know whose sign-off you expect, but I'll help the transfer in any way I can.

However, TPF and the Perl NOC had specifically said they don't want perl.com to use GitHub pages. I wasn't part of that conversation but had the same questions.

Also, immediate publishing has never really been a wanted feature. That stuff already exists though because you can run the Hugo site on a local server. The details are in the Makefile. It's up to you how much work you want to do, but it's not so much that Perl.com needs some new system. It merely needs writers and contents. Everything else is pretty much automated and working fine.

**Comment by oalders** [comment]
> I don't know whose sign-off you expect, but I'll help the transfer in any way I can.

I can ask around at TPF and see what's required.

> However, TPF and the Perl NOC had specifically said they don't want perl.com to use GitHub pages. I wasn't part of that conversation but had the same questions.

Ok, I will see if I can find out what the concern is.

> Also, immediate publishing has never really been a wanted feature. That stuff already exists though because you can run the Hugo site on a local server. The details are in the Makefile. It's up to you how much work you want to do, but it's not so much that Perl.com needs some new system. It merely needs writers and content. Everything else is pretty much automated and working fine.

I think it's more about not having to ask someone to push or deploy something. I have my blog as a Hugo site on render.com. If I create a PR it auto-deploys a staging site so that I can explore what the published site would look like. As someone previewing a PR, I would find that helpful as I can quickly sign off on something while on my phone or somewhere else without having to pull down a PR and deploy it locally.

So, it's probably in the range o 5-10 minutes of work to get it working with render.com If that service ever goes away, it's not hard to find a replacement.

**Comment by oalders** [comment]
I've linked to this issue in #general on on TPF Slack. We'll see what the response is.

**Comment by djzort** [comment]
The community reps meeting in January might be a good place to discuss this more via Zoom.

**Comment by djzort** [comment]
If possible, can we arrange for TPF to acquire ownership of perl dot com so that it doesnt slip away to a doman squatter?

**Comment by briandfoy** [comment]
> If possible, can we arrange for TPF to acquire ownership of perl dot com so that it doesnt slip away to a doman squatter?

The running of the website on perl.com and the maintenance of the domain are different things. Tom Christainsen owns the domain, and the Perl NOC looks after it. That's completely independent of anyone who runs a web server for that domain.

**Comment by toddr** [comment]
I wonder how the NOC would feel about advent.perl.com. Would this be a good idea @oalders ?

**Comment by oalders** [comment]
@toddr not sure what you're asking? https://perladvent.org/ is already hosted at GitHub. I think that `perl.com` could be hosted at GitHub (or even better at render.com) with little effort *unless* there is some special configuration in the current web server setup.

It could just deploy the static site on merges to the main branch and it wouldn't require anyone to push any buttons.

**Comment by oalders** [comment]
@briandfoy who is contact person for the Perl NOC to discuss the site deployment with?

**Comment by briandfoy** [comment]
@oalders noc@perl.org, but also see https://github.com/tpf/perldotcom/issues/342#issuecomment-1366762546

**Comment by briandfoy** [comment]
I think this issue has gone as far as it needs to. If someone needs help with something or wants to be a collaborator in this repo, just ask.
