### ISSUE TITLE
random 404 results on pages that work on previous and subsequent results

### ISSUE THREAD

**Issue by wchristian** [tpf/perldotcom#38]
This happens sometimes. Sorry i don't have more details, but it simply happens sometimes.

Got this in Opera v12.18 with JS off.

![image](https://user-images.githubusercontent.com/175467/34337145-591203fc-e95d-11e7-990c-11d90f5f1b06.png)

**Comment by dnmfarrell** [comment]
Does it happen when clicking an ordinary link?

Were you making thousands of requests in a small amount of time? (wonder if it's our firewall).

**Comment by dnmfarrell** [comment]
I've tested this in Firefox with JS disabled - the homepage loads ok.
