### ISSUE TITLE
search form should indicate it links to DuckDuckGo

### ISSUE THREAD

**Issue by wchristian** [tpf/perldotcom#41]
I expected an actual search, but got only DDG, this was an unwelcome surprise and in the spirit of not surprising the user it should make clear that it's that.

**Comment by dnmfarrell** [comment]
We could change the text to "SEARCH VIA DUCKDUCKGO" but I'm reluctant to do that as It adds a lot of text to the box, we'd have to widen it to accommodate it. Then we'd have to check the implications on the site's media queries, and that the nav displays correctly across a variety of screen widths.

Another option might be superimposing the DDG logo over the search bar, but that sounds like a CSS nightmare.

**Comment by briandfoy** [comment]
i had this idea that the Duck Duck Go text could be greyed text inside the search box. It's cleared when someone starts to type in it. I've seen that sort of thing on other sites.

**Comment by dnmfarrell** [comment]
That's what I was describing in my response. Doing that increases the width of the search box.
