### ISSUE TITLE
Create a comment policy

### ISSUE THREAD

**Issue by briandfoy** [tpf/perldotcom#56]
"Side note: Why aren't comments allowed on Perl.com? A blog without comments isn't a blog." - https://www.reddit.com/r/perl/comments/7r1b33/an_open_letter_to_the_perl_community/dsts4sb/

Basically, tell people Perl.com uses reddit (or whatever) for comments and explain that as a volunteer thing we don't have time or willpower to create and manage such a thing. Link to the reddit comments at the end of each article.

**Comment by mohawk2** [comment]
It seems possible to even embed Reddit comments: the code for that subreddit is available from clicking the top "share" link, then the `<>` button:

```html
<blockquote class="reddit-card" data-card-created="1516319746"><a href="https://www.reddit.com/r/perl/comments/7r1b33/an_open_letter_to_the_perl_community/?ref=share&ref_source=embed">An Open Letter to the Perl Community</a> from <a href="http://www.reddit.com/r/perl">perl</a></blockquote>
<script async src="//embed.redditmedia.com/widgets/platform.js" charset="UTF-8"></script>
```

**Comment by briandfoy** [comment]
Curious. Now the trick is to figure out how to now the right URL to put in there.

**Comment by mohawk2** [comment]
Link in with perlybot, or even use the same thing it does to inject articles on reddit, which will then give you the right URL. “The best way to predict your future is to create it.” ― Abraham Lincoln

**Comment by dnmfarrell** [comment]
This is our policy! https://www.youtube.com/watch?v=tdh0w69h5xI&list=PLA9_Hq3zhoFx1inHPmwmbXrPcI8cc0fyO&index=28&t=22m40s

**Comment by briandfoy** [comment]
For those who don't want to watch David's "Rebuilding Perl.com" talk from TPC 2018 (that youtube link), the comment policy is that we don't have comments on Perl.com. We're volunteers and we don't have the time to manage that (the code, the database, the moderation, session handling, GDPR, and so on). Instead we post the links to reddit.com and let that site handle all the user management, moderation, and so on.
